CREATE DATABASE IF NOT EXISTS greendot_fintech CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE greendot_fintech;
CREATE TABLE IF NOT EXISTS applications (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(200) NOT NULL,
  address VARCHAR(300) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(150) NOT NULL,
  dob DATE NOT NULL,
  ssn_last4 CHAR(4) NOT NULL,
  document_path VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
